spring.application.name=demo

# Base de datos H2 guardada en un archivo local dentro del proyecto (carpeta 'data')
spring.datasource.url=jdbc:h2:file:./data/valledelsol_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dbvalle
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite acceder a la consola web de H2 en http://localhost:8080/h2-console
spring.h2.console.enabled=true
server.port=9090
# Actualiza las tablas autom\u00e1ticamente sin borrar los datos existentes
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:my-secret-key-that-should-be-very-long}
